# This builds an image that contains the resources needed by Dockerfile
#
FROM scratch

# Copy resources downloaded via download_deps.py
COPY cl100k_base.tiktoken libssl1.1_1.1.1f-1ubuntu2_arm64.deb tika-server-standard-3.2.3.jar tika-server-standard-3.2.3.jar.md5 libssl*.deb uv-aarch64-unknown-linux-gnu.tar.gz /

COPY nltk_data /nltk_data

COPY huggingface.co /huggingface.co
